car_wash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('serviceapp.urls')),
    path('account/', include('user.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceapp/urls.py
from django.urls import path
from .views import index, washer_list, washer_detail, create_order, order_detail, orders_list, cars_list

app_name = 'wash'
urlpatterns = [
    path('', index, name='index'),
    path('washers/', washer_list, name='washers'),
    path('<int:pk>/washer/', washer_detail, name='washer_detail'),
    path('orders', orders_list, name='orders'),
    path('order/create', create_order, name='create_order'),
    path('<int:pk>/order/', order_detail, name='order_detail'),
    path('cars', cars_list, name='cars'),

]

user/urls.py
from django.urls import path

from .views import user_login, user_register, user_logout, user_dashboard

app_name = 'user'
urlpatterns = [
    path('login', user_login, name='login'),
    path('register', user_register, name='register'),
    path('logout', user_logout, name='logout'),
    path('profile', user_dashboard, name='dashboard')

]

templates/partials/_footer.html
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; 2021 Car wash Company. <a href="https://webthemez.com/free-bootstrap-templates/" target="_blank"></a>
            </div>
            <div class="col-sm-6">
                <ul class="social-icons">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                    <li><a href="#"><i class="fa fa-github"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/partials/_header.html
{% load static %}

<header id="header">
    <nav id="main-nav" class="navbar navbar-default navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'wash:index' %}"><img
                        src="{% static 'serviceapp/images/logo.png' %}"
                        alt="logo"></a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'wash:index' %}">Home</a></li>
                    <li><a href="{% url 'wash:index' %}">Our Service</a></li>
                    <li><a href="{% url 'wash:index' %}">About Us</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'wash:washers' %}">Washers</a></li>
                        <li><a href="{% url 'wash:orders' %}">Orders</a></li>
                        <li><a href="{% url 'wash:cars' %}">Cars</a></li>

                        <li><a href="{% url 'user:dashboard' %}">Profile</a></li>
                        <li><a>
                            <form action="{% url 'user:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" name="action">Logout</button>
                            </form>
                        </a></li>
                    {% else %}
                        <li><a href="{% url 'user:login' %}">Login</a></li>
                        <li><a href="{% url 'user:register' %}">Register</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
</header>