car_wash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('serviceapp.urls')),
    path('account/', include('user.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceapp/urls.py
from django.urls import path
from .views import index, washer_list, washer_detail, create_order, order_detail, orders_list, cars_list

app_name = 'wash'
urlpatterns = [
    path('', index, name='index'),
    path('washers/', washer_list, name='washers'),
    path('<int:pk>/washer/', washer_detail, name='washer_detail'),
    path('orders', orders_list, name='orders'),
    path('order/create', create_order, name='create_order'),
    path('<int:pk>/order/', order_detail, name='order_detail'),
    path('cars', cars_list, name='cars'),

]

user/urls.py
from django.urls import path

from .views import user_login, user_register, user_logout, user_dashboard

app_name = 'user'
urlpatterns = [
    path('login', user_login, name='login'),
    path('register', user_register, name='register'),
    path('logout', user_logout, name='logout'),
    path('profile', user_dashboard, name='dashboard')

]

templates/pages/cars.html
{% extends 'layout.html' %}
{% block title %} Cars List {% endblock %}


{% load static %}
{% block content %}
    <section id="orders">
        <div class="container">
            <div class="section-header">
                <br>
                <br>
                <h2 class="section-title text-center wow fadeInDown">Cars</h2>
            </div>
            <form class="contact100-form validate-form car-form center" action="/cars" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.errors }}
                    </div>
                {% endif %}
                {% if message %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Licence Plate</span>
                    <div>
                        {{ form.licence_plate }}
                    </div>
                    <span class="focus-input100"></span>
                </div>

                <div class="wrap-input100 input100-select">
                    <span class="label-input100">Car Type</span>
                    <div>
                        {{ form.car_type }}
                    </div>
                    <span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
                    <div class="wrap-contact100-form-btn">
                        <div class="contact100-form-bgbtn"></div>
                        <button class="contact100-form-btn">
							<span>
								Add Car
							</span>
                        </button>
                    </div>
                </div>
            </form>
            <hr>
            <br>
            <br>
            <div class="row">
                {% for car in cars %}
                    <div class="col-md-3 col-sm-6 card-margin ">
                        <a href='#'>
                            <div class="wow fadeInUp car-card" data-wow-duration="400ms" data-wow-delay="0ms">
                                <div class="text-center">
                                    <br>
                                    <h3>{{ car.licence_plate }}</h3>
                                    <h4>Type: {{ car.car_type }}</h4>
                                    <br>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

            {% if cars.has_other_pages %}
                <ul class="pagination">
                    {% if cars.has_previous %}
                        <li><a href="?page={{ cars.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in cars.paginator.page_range %}
                        {% if cars.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if cars.has_next %}
                        <li><a href="?page={{ cars.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/pages/employee.html
{% extends 'layout.html' %}
{% block title %} {{ employee.first_name }} {% endblock %}


{% load static %}
{% block content %}
    <div class="container">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Filter orders
                <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="{% url 'employee_detail' employee.id %}?filter=7">1 Week Orders</a></li>
                <li><a href="{% url 'employee_detail' employee.id %}?filter=31">1 Month Orders</a></li>
                <li><a href="{% url 'employee_detail' employee.id %}?filter=365">1 Year Orders</a></li>
                <li><a href="{% url 'employee_detail' employee.id %}">Clear filters</a></li>

            </ul>
        </div>

        {% if '365' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 Year Orders</h4>
        {% elif '7' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 week Orders</h4>
        {% elif '31' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 month Orders</h4>
        {% endif %}
        <h2 class="section-title text-center wow fadeInDown">{{ employee.first_name }} {{ employee.last_name }}</h2>
        <h4 class="section-title text-center wow fadeInDown">Orders Number: <b>{{ orders.count }}</b></h4>
        <h4 class="section-title text-center wow fadeInDown">Monthly Salary: <b>{{ employee.salary }} ლ</b></h4>
        <h4 class="section-title text-center wow fadeInDown">Bonus: <b>{{ bonus_money }} ლ</b></h4>


        <div class="team-img">
            <img class=" employee-img" src="{{ employee.image.url }}" alt="">
        </div>

        <table class="table table-dark">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Car Number</th>
                <th scope="col">Booth Number</th>
                <th scope="col">time</th>
                <th scope="col">Price</th>
            </tr>
            </thead>
            <tbody>


            {% for order in orders %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.car }}</td>
                    <td>{{ order.booth }}</td>
                    <td>{{ order.end_date }}</td>
                    <td>{{ order.price }}ლ</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


{% endblock %}

templates/pages/index.html
{% extends 'layout.html' %}


{% load static %}
{% block content %}


    <section id="main-slider">
        <div class="owl-carousel">
            <div class="item" style="background-image: url('/static/serviceapp/images/slider/bg1.jpg');">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="carousel-caption">
                                <div class="carousel-content">
                                    <h2>Car Servicing</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elitsed do eiusmod.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style="background-image: url('/static/serviceapp/images/slider/bg2.jpg');">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="carousel-caption">
                                <div class="carousel-content">
                                    <h2>Quick Car Wash</h2>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elitsed do eiusmod.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div><!--/.item-->
        </div><!--/.owl-carousel-->
    </section>
    <section id="services">
        <div class="container">

            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Our Services</h2>
                <p class="text-center wow fadeInDown">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
                    eget
                    risus vitae massa <br> semper aliquam quis mattis quam.</p>
            </div>

            <div class="row">
                <div class="features">
                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms">
                        <div class="media service-box">
                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-heart-o"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Car Wash</h4>
                                <p>Backed by some of the biggest names in the industry, Firefox OS is an open platform
                                    that
                                    fosters greater</p>
                            </div>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="100ms">
                        <div class="media service-box">
                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-line-chart"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Car Servicing</h4>
                                <p>Backed by some of the biggest names in the industry, Firefox OS is an open platform
                                    that
                                    fosters greater</p>
                            </div>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="200ms">
                        <div class="media service-box">
                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-star-o"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Car Checkup</h4>
                                <p>Morbi vitae tortor tempus, placerat leo et, suscipit lectus. Phasellus ut euismod
                                    massa,
                                    eu eleifend ipsum.</p>
                            </div>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                        <div class="media service-box">

                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-clock-o"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Alignment</h4>
                                <p>Morbi vitae tortor tempus, placerat leo et, suscipit lectus. Phasellus ut euismod
                                    massa,
                                    eu eleifend ipsum.</p>
                            </div>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="400ms">
                        <div class="media service-box">
                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-paper-plane-o"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Painting</h4>
                                <p>Morbi vitae tortor tempus, placerat leo et, suscipit lectus. Phasellus ut euismod
                                    massa,
                                    eu eleifend ipsum.</p>
                            </div>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="500ms">
                        <div class="media service-box">
                            <div class="hexagon">
                                <div class="inner">
                                    <i class="fa fa-calendar"></i>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">Modifiying</h4>
                                <p>Morbi vitae tortor tempus, placerat leo et, suscipit lectus. Phasellus ut euismod
                                    massa,
                                    eu eleifend ipsum.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="about">
        <div class="container">

            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">About Us</h2>
                <p class="text-center wow fadeInDown">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
                    eget
                    risus vitae massa <br> semper aliquam quis mattis quam.</p>
            </div>

            <div class="row">
                <div class="col-sm-6 wow fadeInLeft">
                    <img class="img-responsive" src="{% static 'serviceapp/images/about.png' %}" alt="">
                </div>

                <div class="col-sm-6 wow fadeInRight">
                    <h3 class="column-title">High Quality Process</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget risus vitae massa semper
                        aliquam quis mattis quam. Morbi vitae tortor tempus, placerat leo et, suscipit lectus. Phasellus
                        ut
                        euismod massa, eu eleifend ipsum.</p>

                    <p>Nulla eu neque commodo, dapibus dolor eget, dictum arcu. In nec purus eu tellus consequat
                        ultricies.
                        Donec feugiat tempor turpis, rutrum sagittis mi venenatis at. Sed molestie lorem a blandit
                        congue.
                        Ut pellentesque odio quis leo volutpat, vitae vulputate felis condimentum. </p>

                    <p>Praesent vulputate fermentum lorem, id rhoncus sem vehicula eu. Quisque ullamcorper, orci
                        adipiscing
                        auctor viverra, velit arcu malesuada metus, in volutpat tellus sem at justo.</p>


                    <a class="btn btn-primary background-red" href="#">Learn More</a>

                </div>
            </div>
        </div>
    </section><!--/#about-->


    <section id="contact-us">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Contact Us</h2>
                <p class="text-center wow fadeInDown">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
                    eget
                    risus vitae massa <br> semper aliquam quis mattis quam.</p>
            </div>
        </div>
    </section><!--/#contact-us-->


    <section id="contact">

        <div class="container">
            <div class="container contact-info">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <div class="contact-form">
                            <h3>Contact Info</h3>

                            <address>
                                <strong>Car Wash Company.</strong><br>
                                Chavchavadze st 11<br>
                                Georgia<br>
                                <abbr title="Phone">P:</abbr> (123) 456-7890
                            </address>
                        </div>
                    </div>
                    <div class="col-sm-8 col-md-8">
                        <div class="contact-form">

                            <!--NOTE: Update your email Id in "contact_me.php" file in order to receive emails from your contact form-->

                            <form name="sentMessage" id="contactForm" novalidate>
                                <div class="control-group">
                                    <div class="controls">
                                        <input type="text" class="form-control"
                                               placeholder="Full Name" id="name" required
                                               data-validation-required-message="Please enter your name"/>
                                        <p class="help-block"></p>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <div class="controls">
                                        <input type="email" class="form-control" placeholder="Email"
                                               id="email" required
                                               data-validation-required-message="Please enter your email"/>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <div class="controls">
    				 <textarea rows="10" cols="100" class="form-control"
                               placeholder="Message" id="message" required
                               data-validation-required-message="Please enter your message" minlength="5"
                               data-validation-minlength-message="Min 5 characters"
                               maxlength="999" style="resize:none"></textarea>
                                    </div>
                                </div>
                                <div id="success"></div> <!-- For success/fail messages -->
                                <button type="submit" class="btn btn-primary pull-right background-red">Send</button>
                                <br/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/pages/order_details.html
{% extends 'layout.html' %}
{% block title %} Order N{{ order.pk }} {% endblock %}


{% load static %}
{% block content %}
    <div class="container">


        <h1 class="section-title text-center wow fadeInDown">Order Details</h1>
        <br>
        <p class="h4 text-center">Car Licence Plate: <b>{{ order.car.licence_plate }}</b></p>
        <p class="h4 text-center">Car Type: <b>{{ order.car.car_type }}</b></p>
        <br>
        <p class="h4 text-center">Car Wash Type: <b>{{ order.wash_type }}</b></p>
        <p class="h4 text-center">Wash Price: <b>{{ order.price }} GEL</b></p>
        <p class="h4 text-center">Note: <b>{{ order.note }} </b></p>
        <br>
        <p class="h4 text-center">Start Date: <b>{{ order.start_date }} </b></p>
        <p class="h4 text-center">End Date: <b>{{ order.end_date|default:'Not Finished.' }} </b></p>
        <br>
        <p class="h4 text-center">Washer Name: <a
                href="{% url 'wash:washer_detail' order.employee.id %}"><b>{{ order.employee }} </b></a></p>
        <br>


    </div>


{% endblock %}

templates/pages/orders.html
{% extends 'layout.html' %}
{% block title %} Orders List {% endblock %}


{% load static %}
{% block content %}
    <section id="orders">
        <div class="container">
            <div class="dropdown">
                <br>
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Filter Orders
                    <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'wash:orders' %}?finished=True">Finished Orders</a></li>
                    <li><a href="{% url 'wash:orders' %}">Clear Filter</a></li>

                </ul>
            </div>
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Orders</h2>
            </div>
            <a href="{% url 'wash:create_order' %}" class="btn btn-primary btn-lg btn-block background-red">Create
                Order</a>
            <br>
            <br>
            <div class="row">
                {% for order in orders %}
                    <div class="col-md-3 col-sm-6 card-margin">
                        <a href='{% url 'wash:order_detail' order.id %}'>
                            <div class="wow fadeInUp" data-wow-duration="400ms" data-wow-delay="0ms">
                                <div class="team-img">
                                    <img class="img-responsive"
                                         src="{% static 'serviceapp/images/prettyPhoto/order.jpeg' %}"
                                         alt="">
                                </div>
                                <div class="text-center">
                                    <h3>Order N{{ forloop.counter }}</h3>
                                    <h4>{{ order.price }}GEL</h4>
                                    <h6>{{ order.start_date }}</h6>
                                    <span>Order Detail</span>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            {% if orders.has_other_pages %}
                <ul class="pagination">
                    {% if orders.has_previous %}
                        <li><a href="?page={{ orders.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in orders.paginator.page_range %}
                        {% if orders.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if orders.has_next %}
                        <li><a href="?page={{ orders.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/pages/team.html
{% extends 'layout.html' %}
{% block title %} Our Team {% endblock %}


{% load static %}
{% block content %}

    <section id="our-team">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Washer Team</h2>
            </div>

            <div class="row">
                {% for employee in employees %}
                    <div class="col-md-3 col-sm-6">
                        <a href='{% url 'employee_detail' employee.id  %}'>
                            <div class="team-member wow fadeInUp" data-wow-duration="400ms" data-wow-delay="0ms">
                                <div class="team-img">
                                    <img class="img-responsive" src="{{ employee.image.url }}" alt="">
                                </div>
                                <div class="team-info">
                                    <h3>{{ employee.name }} {{ employee.lastname }}</h3>
                                    <span>Washer</span>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>

{% endblock %}

templates/pages/washer_details.html
{% extends 'layout.html' %}
{% block title %} {{ employee.first_name }} {% endblock %}


{% load static %}
{% block content %}
    <div class="container">
        <div class="dropdown">
            <br>
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Filter orders
                <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="{% url 'wash:washer_detail' washer.id %}?filter=7">1 Week Orders</a></li>
                <li><a href="{% url 'wash:washer_detail' washer.id %}?filter=31">1 Month Orders</a></li>
                <li><a href="{% url 'wash:washer_detail' washer.id %}?filter=365">1 Year Orders</a></li>
                <li><a href="{% url 'wash:washer_detail' washer.id %}">Clear filters</a></li>

            </ul>
        </div>

        {% if '365' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 Year Orders</h4>
        {% elif '7' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 week Orders</h4>
        {% elif '31' == filter_day %}
            <h4 class="section-title text-center wow fadeInDown">1 month Orders</h4>
        {% endif %}
        <h2 class="section-title text-center wow fadeInDown">{{ washer.first_name }} {{ washer.last_name }}</h2>
        <h4 class="section-title text-center wow fadeInDown">Orders Number: <b>{{ orders.count }}</b></h4>
        <h4 class="section-title text-center wow fadeInDown">Monthly Salary: <b>{{ washer.salary }} ლ</b></h4>
        <h4 class="section-title text-center wow fadeInDown">Bonus: <b>{{ bonus_money }} ლ</b></h4>


        <div class="team-img">
            <img class=" employee-img" src="{{ washer.image.url }}" alt="">
        </div>

        <table class="table table-dark">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Car Number</th>
                <th scope="col">Booth Number</th>
                <th scope="col">time</th>
                <th scope="col">Price</th>
                <th scope="col">Details</th>
            </tr>
            </thead>
            <tbody>


            {% for order in orders %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.car }}</td>
                    <td>{{ order.booth }}</td>
                    <td>{{ order.end_date }}</td>
                    <td>{{ order.price }}ლ</td>
                    <td><a href="{% url 'wash:order_detail' order.pk %}" class="btn ">Order Details</a></td>

                    <th>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


{% endblock %}

templates/pages/washers.html
{% extends 'layout.html' %}
{% block title %} Our Team {% endblock %}


{% load static %}
{% block content %}

    <section id="our-team">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Washer Team</h2>
            </div>

            <div class="row">
                {% for washer in washers %}
                    <div class="col-md-3 col-sm-6">
                        <a href='{% url 'wash:washer_detail' washer.id  %}'>
                            <div class="team-member wow fadeInUp" data-wow-duration="400ms" data-wow-delay="0ms">
                                <div class="team-img">
                                    <img class="img-responsive" src="{{ washer.image.url }}" alt="">
                                </div>
                                <div class="team-info">
                                    <h3>{{ washer.name }} {{ washer.lastname }}</h3>
                                    <span>Washer</span>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>

{% endblock %}